import fs from 'node:fs/promises';
import path from 'node:path';

// Include the full license of every npm package represented in either bundle.
// Fail the build if an upstream release drops its license instead of silently
// shipping an incomplete attribution file.
export async function writeLicenses(metafiles) {
  const roots = new Set();
  for (const meta of metafiles) for (const input of Object.keys(meta.inputs)) {
    const match = input.replaceAll('\\', '/').match(/^(.*node_modules\/(?:@[^/]+\/)?[^/]+)/);
    if (match) roots.add(match[1]);
  }
  const entries = [];
  for (const root of [...roots].sort()) {
    const pkg = JSON.parse(await fs.readFile(path.join(root, 'package.json'), 'utf8'));
    const files = (await fs.readdir(root)).filter(f => /^(licen[cs]e|copying|notice)([.\-_]|$)/i.test(f)).sort();
    if (!files.length) throw new Error(`Missing bundled license: ${pkg.name}`);
    const body = await Promise.all(files.map(async file => `--- ${file} ---\n${await fs.readFile(path.join(root, file), 'utf8')}`));
    entries.push(`${pkg.name} ${pkg.version}\nLicense: ${pkg.license || 'See text below'}\n\n${body.join('\n')}`);
  }
  await fs.mkdir('resources/licenses', { recursive: true });
  await fs.writeFile('resources/licenses/BUNDLED-DEPENDENCIES.txt', `Generated by npm run build from the actual esbuild inputs.\nPython sources have separate notices in robot/UPSTREAM.md.\n\n${entries.join('\n\n' + '='.repeat(80) + '\n\n')}`);
  console.log(`Bundled license notices: ${entries.length} packages.`);
}
